For you to Following
pinkary-project/pinkary.com pull request #494
Opened 2024-08-08 00:11 UTC by msamgan

#453

<img width="855" alt="image" src="https://github.com/user-attachments/assets/5cc495bb-6535-41cf-b67f-e0c5d737d341">

2024-08-26 06:26 UTC, MrPunyapal requested changes

2024-08-27 17:03 UTC, msamgan commented on app/Queries/Feeds/QuestionsFollowingFeed.php
> +final readonly class QuestionsFollowingFeed
I hear you, but the logic for follower and following is not touched at all. That makes the need to change in query, not required.

Its just the label and files names which will be impacted. At DB level there is no change hence no update in Query.

what am I missing ?

2024-08-27 17:06 UTC, MrPunyapal commented on app/Queries/Feeds/QuestionsFollowingFeed.php
> +final readonly class QuestionsFollowingFeed
it should show what exactly the following means.

2024-08-27 17:13 UTC, msamgan commented on app/Queries/Feeds/QuestionsFollowingFeed.php
> +final readonly class QuestionsFollowingFeed
can you please elaborate for better understanding ?

2024-08-27 17:34 UTC, msamgan commented on app/Queries/Feeds/QuestionsFollowingFeed.php
> +final readonly class QuestionsFollowingFeed
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/3273cec0-95da-4cc2-bc78-df7ea470b7dc">


Its exactly what you are saying.  the query is on $question->to only.

2024-08-27 20:43 UTC, ojessecruz commented on app/Queries/Feeds/QuestionsFollowingFeed.php
> +final readonly class QuestionsFollowingFeed
@msamgan it's the same logic on Twitter/X. The Following tab, should show just the posts from the users you are currently following.

What @MrPunyapal is saying, is you need to change the entire logic here to make sense to change the Tab's name,

2024-08-28 13:57 UTC, msamgan commented on app/Queries/Feeds/QuestionsFollowingFeed.php
> +final readonly class QuestionsFollowingFeed
thanks for the input @ojessecruz . The I got that part, but the current query is doing exactly the same. That is what i did not undertand. What are the changes required.

The for you page right now shows the post from the people you are are following. The last line in the query (image above) shows the same. This is what I am confused about.

2024-08-28 16:23 UTC, MrPunyapal commented on app/Queries/Feeds/QuestionsFollowingFeed.php
> +final readonly class QuestionsFollowingFeed
When you see orWhere that means it's not just including following posts it has some extra sutff that we need to remove 🙂

2024-08-28 16:24 UTC, lpheller commented on app/Queries/Feeds/QuestionsFollowingFeed.php
> +final readonly class QuestionsFollowingFeed
No, the query loads records that are created by people who’s posts you liked in the past (60 days). 

If I liked one of your posts / questions yesterday but I’m not following you - your posts would still appear in the for you page.

2024-08-29 03:18 UTC, msamgan commented on app/Queries/Feeds/QuestionsFollowingFeed.php
> +final readonly class QuestionsFollowingFeed
Ohhh.. This is what you meant. You meant only the post from followings. Right now it also shows the liked and replied posts by the following. Thanks for the explanation. I'll make the update tomorrow.

Thanks @MrPunyapal

2024-09-06 17:19 UTC, MrPunyapal commented on app/Queries/Feeds/QuestionsFollowingFeed.php
> +final readonly class QuestionsFollowingFeed
@msamgan are you there?

2024-09-06 17:59 UTC, msamgan commented on app/Queries/Feeds/QuestionsFollowingFeed.php
> +final readonly class QuestionsFollowingFeed
yes, was preoccupied in some family matter.
Will give you an updated PR by tomorrow...

2024-09-11 15:52 UTC, closed without merging