fix: add error handling for QR code generation
pinkary-project/pinkary.com pull request #666
Opened 2024-09-24 10:11 UTC by monayemislam

This pull request addresses an issue in the QrCodeController where potential exceptions during QR code generation were not being handled. I have added a try-catch block around the QR code generation logic to handle potential exceptions in `app/Http/Controllers/QrCodeController.php`

2024-09-24 15:56 UTC, MrPunyapal requested changes

2024-09-24 15:56 UTC, MrPunyapal commented on app/Http/Controllers/QrCodeController.php
> +        } catch (\Exception $e) {
can you show any case? (I mean if exception is handled how we gonna know that it has error?
we must know what exception it can throw.

2024-09-24 17:59 UTC, monayemislam reviewed
Here I have mentioned the possible reasons of exceptions. Simply, if you put `->size(-1)` where -1 is an invalid parameter then you'll get an Invalid Argument error.

2024-09-25 01:59 UTC, MrPunyapal commented
Can you add tests for the same?

2024-09-30 07:18 UTC, nunomaduro commented
We can't shown an 500 to the user.

2024-09-30 07:18 UTC, closed without merging